global:
  scrape_interval: 15s # Frequência de coleta (15s é um padrão seguro)

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      # 'postgres-exporter' é o nome do serviço que definimos no docker-compose
      - targets: ['postgres-exporter:9187']