global:
  scrape_interval: 15s # collector frequency (15s secure value)

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']      

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']